name: Deploy documentation

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

jobs:
  build-publish:
    name: build-move-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Maven
        run: mvn clean package --projects :docs --batch-mode -Pbuild-docs

      - name: Move
        run: |
          mkdir public
          mv docs/target/public/index.html docs/index.html

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}